Restart winrm
flcdrg/au-packages pull request #120
Opened 2021-12-08 18:54 UTC by Plork

add the option to disable the restart of winrm with admin center install.

2021-12-08 22:39 UTC, flcdrg commented
Thanks for the PR!

Given I presume you'd only want to use this to disable the restart, I'm thinking it might be nicer to make this an 'opt-in' parameter..

eg call it '\DisableRestartWinRM` and only add it to the args list if it is passed in:

```
if ($pp['RESTARTWINRM']) {
    $restart_winrm = "RESTART_WINRM=0"
}
```

2021-12-09 08:32 UTC, Plork commented
fine with me, thats the only discussion I was looking for ;) was exactly my internal debat.

naming parameters is alway the hardest thing :D

Will change the script

2021-12-09 10:02 UTC, Plork commented
I rewrote arguments to be more clear for optional flags.
also less struggles with quotes like this.

apologies for my editor removing trailing spaces :S

2021-12-13 21:32 UTC, flcdrg commented
I tested this out, but it failed. Missing a space I think

```text
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\david\AppData\Local\Temp\chocolatey\windows-admin-center\1.3.44065.0\WindowsAdminCenter2110.msi" /qn norestart SME_PORT=6516 SSL_CERTIFICATE_OPTION=generate RESTART_WINRM=0/l*v "C:\Users\david\AppData\Local\Temp\chocolatey\windows-admin-center.1.3.44065.0.MsiInstall.log" ] was not successful. Exit code was '1639'. Exit code indicates the following: The command line arguments passed to the MSI are incorrect. If you passed in additional arguments, please adjust. Otherwise followup with the package maintainer(s) to get this fixed. This is most likely an issue with the 'windows-admin-center' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of windows-admin-center was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windows-admin-center\tools\chocolateyinstall.ps1'.
 See log for details.
```

2021-12-13 21:33 UTC, flcdrg requested changes

2021-12-13 21:33 UTC, flcdrg commented on windows-admin-center/tools/chocolateyinstall.ps1
> +$arguments += '/l*v "{0}\{1}.{2}.MsiInstall.log"' -f $env:Temp, $packageName, $env:chocolateyPackageVersion
```suggestion
$arguments += ' /l*v "{0}\{1}.{2}.MsiInstall.log"' -f $env:Temp, $packageName, $env:chocolateyPackageVersion
```

2021-12-13 21:33 UTC, flcdrg commented on windows-admin-center/windows-admin-center.nuspec
> + * `/DisableRestartWinrm:` -  If you are installing with an automation solution that would be broken by the WinRM service restarting, you can disable this by passing this parameter
```suggestion
 * `/DisableRestartWinrm` -  If you are installing with an automation solution that would be broken by the WinRM service restarting, you can disable this by passing this parameter
```

2021-12-15 14:14 UTC, Plork commented
thnx for the test!! I missed those

2021-12-16 08:38 UTC, flcdrg approved these changes

2021-12-16 08:41 UTC, merged

2021-12-16 08:50 UTC, flcdrg commented
I've pushed a new version with this change. Hopefully it will appear soon